### ISSUE TITLE
Make it compatible with Storybook v3

### ISSUE THREAD

**Issue by glambert** [evgenykochetkov/react-storybook-addon-static-markup#3]
This addon does not work with Storybook v3.

Since storybook changed its libraries names, [replacing lib names](https://github.com/storybooks/storybook/blob/master/MIGRATION.md) are required:

`@kadira/storybook` -> `@storybook/react`
`@kadira/storybook-addons` -> `@storybook/addons`

Are you still maintaining this project? I could open a PR for this. Let me know!

**Comment by evgenykochetkov** [comment]
Thanks, done!
